[package]
name = "sec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sec ={ path = "sec" } # path dependency for the binary inside sec
