[env]
# Set even if already present in environment
# CC = { value = "zig cc -target aarch64-linux-gnu", force = true }

# Set even if already present in environment
CC = { value = "zig cc -static -target aarch64-linux-musl", force = true }
CC_aarch64_unknown_linux_musl = { value = "zig cc -static -target aarch64-linux-musl", force = true }

[alias]     # command aliases
x86_linux = "--target x86_64-unknown-linux-musl"
aarch_linux = "--target aarch64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
linker = "/app/.cargo/linker/linux/aarch64/zigcc-musl"
rustflags = [
    "-C", "target-feature=+crt-static",
   "-C", "link-self-contained=yes", #DO NOT USE self-contained libs shipped by some rust toolchains
    ]

[target.x86_64-unknown-linux-musl]
linker = "/app/.cargo/linker/linux/x86_64/zigcc-musl"
rustflags = [
    "-C", "target-feature=+crt-static",
   "-C", "link-self-contained=yes", #DO NOT USE self-contained libs shipped by some rust toolchains
    ]